version: '3'
services:


    nginx:
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./src/main/webapp/setup/index.html:/usr/share/nginx/html/index.html
        - "/home/pinhas/Documents/pinhas_lavagna/lavagna/project/src/main/webapp:/usr/share/nginx/html/static/"
      # ports:
      #   - 8080:8080
      networks:
        - frontend

    app:
      build: .
      ports:
        - "8080:8080"
      networks:
        - frontend
        - backend
      
         

    mysql:
      image: mysql:5.7
      environment: 
             MYSQL_ROOT_PASSWORD: pass
      # ports:
      #     - "81:3306"
      
            
      volumes:
        #- my_sql:/var/lib/mysql
        - ./data.sql:/docker-entrypoint-initdb.d/data.sql
      networks:
        - backend
    
# volumes:
#     my_sql:
networks:
    frontend:
    backend:
      


    