version: '3'
services:
    app:
      build: .
      ports:
          - 8080:8080
      
         

    mysql:
      image: mysql:5.7
      environment: 
             MYSQL_ROOT_PASSWORD: pass
      # ports:
      #     - "81:3306"
      
            
      volumes:
#        - my_sql:/var/lib/mysql
        - ./data.sql:/docker-entrypoint-initdb.d/data.sql
        

      


    