version: '3'
services:


    nginx:
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./src/main/webapp/setup/index.html:/usr/share/nginx/html/index.html
        - "./src/main/webapp:/usr/share/nginx/html/static/"
      depends_on:
            - app
      ports:
          - "80:80"
      networks:
        - frontend

    app:
      build: .
      # ports:
      #   - "8080:8080"
      depends_on:
         - mysql
      networks:
        - frontend
        - backend
      
         

    mysql:
       image: mysql:5.7
       environment: 
              MYSQL_ROOT_PASSWORD: pass
           
       volumes:
         - my_db:/var/lib/mysql
         - ./data.sql:/docker-entrypoint-initdb.d/data.sql
       networks:
         - backend
    

    server:
       image: "my_doc"
       build:
        context: .
        dockerfile: Dockerfile_docu
       ports:
         - "8081:45001" 

    
volumes:
    my_db:

networks:
    frontend:
    backend:
      


    